allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@vitest/expect@4.1.9'
  - '@vitest/mocker@4.1.9'
  - '@vitest/pretty-format@4.1.9'
  - '@vitest/runner@4.1.9'
  - '@vitest/snapshot@4.1.9'
  - '@vitest/spy@4.1.9'
  - '@vitest/utils@4.1.9'
  - astro@7.2.0
  - vitest@4.1.9
  - tsx@4.23.10

overrides:
  "@iconify/tools": "^5.0.12"
  esbuild: "^0.28.1"
